version: '3.1'

services:
  front:
    container_name: front
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  
  back:
    container_name: back
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
